export type CategoryKey =
  | "concerts"
  | "nightclubs"
  | "bars"
  | "restaurants"
  | "beach"
  | "cinema"
  | "hotels"
  | "festivals"
  | "sport"
  | "culture"
  | "comedy"
  | "liveMusic";

export const CATEGORIES: { key: CategoryKey; icon: string; color: string }[] = [
  { key: "concerts", icon: "musical-notes", color: "#E8735A" },
  { key: "nightclubs", icon: "wine", color: "#9B8FE8" },
  { key: "bars", icon: "beer", color: "#D4AF37" },
  { key: "restaurants", icon: "restaurant", color: "#4CAF82" },
  { key: "beach", icon: "sunny", color: "#5AB4E8" },
  { key: "cinema", icon: "film", color: "#E85A9B" },
  { key: "hotels", icon: "bed", color: "#8FE8B0" },
  { key: "festivals", icon: "sparkles", color: "#E8C85A" },
  { key: "sport", icon: "football", color: "#5AE875" },
  { key: "culture", icon: "library", color: "#B85AE8" },
  { key: "comedy", icon: "happy", color: "#E8985A" },
  { key: "liveMusic", icon: "mic", color: "#5A9BE8" },
];

export const VENUE_TYPES = [
  "Nightclub",
  "Bar",
  "Restaurant",
  "Concert Hall",
  "Beach Club",
  "Cinema",
  "Hotel",
  "Stadium",
  "Cultural Center",
  "Comedy Club",
];

export const COUNTRIES = [
  { code: "TG", name: "Togo",  emoji: "🇹🇬" },
  { code: "BJ", name: "Bénin", emoji: "🇧🇯" },
] as const;

export type CountryCode = typeof COUNTRIES[number]["code"];

export const MOCK_CITIES = [
  { id: "lome",         name: "Lomé",           country: "Togo", emoji: "🏙️", latitude: 6.1374,  longitude: 1.2123 },
  { id: "tsevie",       name: "Tsévié",          country: "Togo", emoji: "🏘️", latitude: 6.4247,  longitude: 1.2159 },
  { id: "aneho",        name: "Aného",           country: "Togo", emoji: "🏖️", latitude: 6.2291,  longitude: 1.5970 },
  { id: "vogan",        name: "Vogan",           country: "Togo", emoji: "🌾", latitude: 6.2676,  longitude: 1.5258 },
  { id: "tabligbo",     name: "Tabligbo",        country: "Togo", emoji: "🌿", latitude: 6.5826,  longitude: 1.5013 },
  { id: "notse",        name: "Notsé",           country: "Togo", emoji: "🎶", latitude: 6.9495,  longitude: 1.1715 },
  { id: "kpalime",      name: "Kpalimé",         country: "Togo", emoji: "🌿", latitude: 6.9004,  longitude: 0.6237 },
  { id: "badou",        name: "Badou",           country: "Togo", emoji: "🏞️", latitude: 7.5769,  longitude: 0.5979 },
  { id: "amlame",       name: "Amlamé",          country: "Togo", emoji: "🌱", latitude: 7.3667,  longitude: 0.9167 },
  { id: "atakpame",     name: "Atakpamé",        country: "Togo", emoji: "🎵", latitude: 7.5328,  longitude: 1.1244 },
  { id: "blitta",       name: "Blitta",          country: "Togo", emoji: "🌻", latitude: 8.3167,  longitude: 0.9833 },
  { id: "sotouboua",    name: "Sotouboua",       country: "Togo", emoji: "🌄", latitude: 8.5667,  longitude: 0.9833 },
  { id: "sokode",       name: "Sokodé",          country: "Togo", emoji: "🎪", latitude: 8.9833,  longitude: 1.1333 },
  { id: "tchamba",      name: "Tchamba",         country: "Togo", emoji: "🏔️", latitude: 9.0333,  longitude: 1.4167 },
  { id: "kara",         name: "Kara",            country: "Togo", emoji: "🎭", latitude: 9.5511,  longitude: 1.1811 },
  { id: "bassar",       name: "Bassar",          country: "Togo", emoji: "⛏️", latitude: 9.2534,  longitude: 0.7812 },
  { id: "niamtougou",   name: "Niamtougou",      country: "Togo", emoji: "✈️", latitude: 9.7665,  longitude: 1.0972 },
  { id: "kande",        name: "Kandé",           country: "Togo", emoji: "🏡", latitude: 9.9447,  longitude: 1.0695 },
  { id: "guerin_kouka", name: "Guérin-Kouka",    country: "Togo", emoji: "🌲", latitude: 9.8667,  longitude: 0.5833 },
  { id: "pagouda",      name: "Pagouda",         country: "Togo", emoji: "🗻", latitude: 9.7444,  longitude: 1.3333 },
  { id: "mango",        name: "Mango",           country: "Togo", emoji: "🥭", latitude: 10.3651, longitude: 0.4714 },
  { id: "dapaong",      name: "Dapaong",         country: "Togo", emoji: "🌅", latitude: 10.8667, longitude: 0.2167 },
  { id: "cinkasse",     name: "Cinkassé",        country: "Togo", emoji: "🌐", latitude: 10.9833, longitude: -0.0167 },

  // Bénin
  { id: "cotonou",      name: "Cotonou",         country: "Bénin", emoji: "🏙️", latitude: 6.3703,  longitude: 2.3912 },
  { id: "porto-novo",   name: "Porto-Novo",      country: "Bénin", emoji: "🏛️", latitude: 6.4969,  longitude: 2.6289 },
  { id: "parakou",      name: "Parakou",         country: "Bénin", emoji: "🌾", latitude: 9.3370,  longitude: 2.6303 },
  { id: "abomey",       name: "Abomey",          country: "Bénin", emoji: "🏰", latitude: 7.1850,  longitude: 1.9912 },
  { id: "djougou",      name: "Djougou",         country: "Bénin", emoji: "🌿", latitude: 9.7090,  longitude: 1.6660 },
  { id: "natitingou",   name: "Natitingou",      country: "Bénin", emoji: "🏔️", latitude: 10.3167, longitude: 1.3833 },
  { id: "ouidah",       name: "Ouidah",          country: "Bénin", emoji: "🏖️", latitude: 6.3622,  longitude: 2.0852 },
  { id: "bohicon",      name: "Bohicon",         country: "Bénin", emoji: "🌴", latitude: 7.1782,  longitude: 2.0667 },

  // Côte d'Ivoire
  { id: "abidjan",      name: "Abidjan",         country: "Côte d'Ivoire", emoji: "🌆", latitude: 5.3600,  longitude: -4.0083 },
  { id: "yamoussoukro", name: "Yamoussoukro",    country: "Côte d'Ivoire", emoji: "🏛️", latitude: 6.8276,  longitude: -5.2893 },
  { id: "bouake",       name: "Bouaké",          country: "Côte d'Ivoire", emoji: "🌳", latitude: 7.6906,  longitude: -5.0301 },
  { id: "san-pedro",    name: "San-Pédro",       country: "Côte d'Ivoire", emoji: "🏖️", latitude: 4.7485,  longitude: -6.6363 },
  { id: "korhogo",      name: "Korhogo",         country: "Côte d'Ivoire", emoji: "🌾", latitude: 9.4580,  longitude: -5.6294 },
  { id: "daloa",        name: "Daloa",           country: "Côte d'Ivoire", emoji: "🌿", latitude: 6.8770,  longitude: -6.4502 },
  { id: "man",          name: "Man",             country: "Côte d'Ivoire", emoji: "🏔️", latitude: 7.4128,  longitude: -7.5536 },
  { id: "grand-bassam", name: "Grand-Bassam",    country: "Côte d'Ivoire", emoji: "🏝️", latitude: 5.2118,  longitude: -3.7383 },

  // Ghana
  { id: "accra",        name: "Accra",           country: "Ghana", emoji: "🏙️", latitude: 5.6037,  longitude: -0.1870 },
  { id: "kumasi",       name: "Kumasi",          country: "Ghana", emoji: "🌳", latitude: 6.6885,  longitude: -1.6244 },
  { id: "tamale",       name: "Tamale",          country: "Ghana", emoji: "🌾", latitude: 9.4035,  longitude: -0.8424 },
  { id: "takoradi",     name: "Takoradi",        country: "Ghana", emoji: "🏖️", latitude: 4.8845,  longitude: -1.7554 },
  { id: "cape-coast",   name: "Cape Coast",      country: "Ghana", emoji: "🏰", latitude: 5.1054,  longitude: -1.2466 },
  { id: "ho",           name: "Ho",              country: "Ghana", emoji: "🌿", latitude: 6.6000,  longitude: 0.4667 },
  { id: "sunyani",      name: "Sunyani",         country: "Ghana", emoji: "🌳", latitude: 7.3349,  longitude: -2.3268 },
  { id: "tema",         name: "Tema",            country: "Ghana", emoji: "🚢", latitude: 5.6698,  longitude: -0.0166 },

  // Burkina Faso
  { id: "ouagadougou",  name: "Ouagadougou",     country: "Burkina Faso", emoji: "🏙️", latitude: 12.3714, longitude: -1.5197 },
  { id: "bobo-dioulasso",name: "Bobo-Dioulasso", country: "Burkina Faso", emoji: "🎶", latitude: 11.1771, longitude: -4.2979 },
  { id: "koudougou",    name: "Koudougou",       country: "Burkina Faso", emoji: "🌾", latitude: 12.2530, longitude: -2.3622 },
  { id: "ouahigouya",   name: "Ouahigouya",      country: "Burkina Faso", emoji: "🌵", latitude: 13.5828, longitude: -2.4214 },
  { id: "banfora",      name: "Banfora",         country: "Burkina Faso", emoji: "🌿", latitude: 10.6308, longitude: -4.7596 },
  { id: "kaya",         name: "Kaya",            country: "Burkina Faso", emoji: "🏘️", latitude: 13.0917, longitude: -1.0850 },
  { id: "fada-ngourma", name: "Fada N'Gourma",   country: "Burkina Faso", emoji: "🌾", latitude: 12.0617, longitude: 0.3585 },

  // Sénégal
  { id: "dakar",        name: "Dakar",           country: "Sénégal", emoji: "🏙️", latitude: 14.7167, longitude: -17.4677 },
  { id: "thies",        name: "Thiès",           country: "Sénégal", emoji: "🌾", latitude: 14.7910, longitude: -16.9359 },
  { id: "saint-louis",  name: "Saint-Louis",     country: "Sénégal", emoji: "🏛️", latitude: 16.0179, longitude: -16.4896 },
  { id: "kaolack",      name: "Kaolack",         country: "Sénégal", emoji: "🥜", latitude: 14.1652, longitude: -16.0726 },
  { id: "ziguinchor",   name: "Ziguinchor",      country: "Sénégal", emoji: "🌿", latitude: 12.5681, longitude: -16.2719 },
  { id: "touba",        name: "Touba",           country: "Sénégal", emoji: "🕌", latitude: 14.8500, longitude: -15.8833 },
  { id: "mbour",        name: "Mbour",           country: "Sénégal", emoji: "🏖️", latitude: 14.4198, longitude: -16.9648 },
  { id: "rufisque",     name: "Rufisque",        country: "Sénégal", emoji: "🚢", latitude: 14.7167, longitude: -17.2667 },
];

export const MOCK_EVENTS = [
  {
    id: "1",
    title: "Afrobeats Night Lomé",
    titleFr: "Nuit Afrobeats Lomé",
    description: "The biggest afrobeats party of the year at Club Byblos with top Togolese DJs",
    descriptionFr: "La plus grande fête afrobeats de l'année au Club Byblos avec les meilleurs DJs togolais",
    date: "2026-04-15",
    time: "22:00",
    venue: "Club Byblos",
    venueId: "v1",
    city: "Lomé",
    category: "nightclubs",
    imageUrl: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1574236170880-2ebea3d4b6d0?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&auto=format&fit=crop",
    ],
    price: 5000,
    currency: "FCFA",
    isSponsored: true,
    status: "approved",
    ticketTypes: [
      { id: "t1", name: "VIP", nameFr: "VIP", price: 20000, currency: "FCFA", available: 50 },
      { id: "t2", name: "Standard", nameFr: "Standard", price: 5000, currency: "FCFA", available: 200 },
    ],
    latitude: 6.1302,
    longitude: 1.2199,
    createdAt: "2026-03-01",
  },
  {
    id: "2",
    title: "Gospel Live at Palais des Congrès",
    titleFr: "Gospel Live au Palais des Congrès",
    description: "Live gospel concert featuring Togo's top gospel artists",
    descriptionFr: "Concert gospel live avec les meilleurs artistes gospel du Togo",
    date: "2026-04-22",
    time: "19:00",
    venue: "Palais des Congrès de Lomé",
    venueId: "v2",
    city: "Lomé",
    category: "concerts",
    imageUrl: "https://images.unsplash.com/photo-1501386761578-eaa54b9f4bcd?w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1501386761578-eaa54b9f4bcd?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1470019693664-1d202d2c0907?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800&auto=format&fit=crop",
    ],
    price: 3000,
    currency: "FCFA",
    isSponsored: false,
    status: "approved",
    ticketTypes: [
      { id: "t3", name: "VIP Gold", nameFr: "VIP Or", price: 15000, currency: "FCFA", available: 20 },
      { id: "t4", name: "VIP", nameFr: "VIP", price: 8000, currency: "FCFA", available: 100 },
      { id: "t5", name: "Standard", nameFr: "Standard", price: 3000, currency: "FCFA", available: 500 },
    ],
    latitude: 6.1328,
    longitude: 1.2167,
    createdAt: "2026-03-05",
  },
  {
    id: "3",
    title: "Comedy Night at Alliance Française",
    titleFr: "Soirée Comédie à l'Alliance Française",
    description: "The best Togolese comedians on one stage",
    descriptionFr: "Les meilleurs comédiens togolais sur une scène",
    date: "2026-05-01",
    time: "20:30",
    venue: "Alliance Française de Lomé",
    venueId: "v3",
    city: "Lomé",
    category: "comedy",
    imageUrl: "https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1527224538127-2104bb71c51b?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1595769816263-9b910be24d5f?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1518310952931-b1de897abd40?w=800&auto=format&fit=crop",
    ],
    price: 2000,
    currency: "FCFA",
    isSponsored: false,
    status: "approved",
    ticketTypes: [
      { id: "t6", name: "VIP", nameFr: "VIP", price: 6000, currency: "FCFA", available: 30 },
      { id: "t7", name: "Standard", nameFr: "Standard", price: 2000, currency: "FCFA", available: 200 },
    ],
    latitude: 6.1374,
    longitude: 1.2111,
    createdAt: "2026-03-10",
  },
  {
    id: "4",
    title: "Festival des Arts de Lomé",
    titleFr: "Festival des Arts de Lomé",
    description: "Annual cultural festival celebrating Togolese art, music and traditions",
    descriptionFr: "Festival culturel annuel célébrant l'art, la musique et les traditions togolaises",
    date: "2026-05-10",
    time: "16:00",
    venue: "Place de l'Indépendance",
    venueId: "v4",
    city: "Lomé",
    category: "festivals",
    imageUrl: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1547153760-18fc86324498?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800&auto=format&fit=crop",
    ],
    price: 0,
    currency: "FCFA",
    isSponsored: true,
    status: "approved",
    ticketTypes: [
      { id: "t8", name: "Free", nameFr: "Gratuit", price: 0, currency: "FCFA", available: 5000 },
    ],
    latitude: 6.1256,
    longitude: 1.2254,
    createdAt: "2026-03-15",
  },
  {
    id: "5",
    title: "Beach Party Aného",
    titleFr: "Soirée Plage d'Aného",
    description: "Epic beach party on the Togolese coast with afro-house music",
    descriptionFr: "Soirée épique sur la côte togolaise avec de la musique afro-house",
    date: "2026-06-05",
    time: "14:00",
    venue: "Le Byblos Beach Aného",
    venueId: "v5",
    city: "Aného",
    category: "beach",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1533760881669-80db4d7b4c15?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1530053969600-caed2596d242?w=800&auto=format&fit=crop",
    ],
    price: 3000,
    currency: "FCFA",
    isSponsored: true,
    status: "approved",
    ticketTypes: [
      { id: "t9", name: "VIP Table", nameFr: "Table VIP", price: 25000, currency: "FCFA", available: 10 },
      { id: "t10", name: "Standard", nameFr: "Standard", price: 3000, currency: "FCFA", available: 300 },
    ],
    latitude: 6.2310,
    longitude: 1.5800,
    createdAt: "2026-03-20",
  },
  {
    id: "6",
    title: "Festival des Cascades de Kpalimé",
    titleFr: "Festival des Cascades de Kpalimé",
    description: "Discover Togolese cuisine and cultural traditions at the foot of the waterfalls",
    descriptionFr: "Découvrez la cuisine et les traditions culturelles togolaises au pied des cascades",
    date: "2026-06-20",
    time: "10:00",
    venue: "Espace Culturel Kpalimé",
    venueId: "v6",
    city: "Kpalimé",
    category: "culture",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&auto=format&fit=crop",
    ],
    price: 0,
    currency: "FCFA",
    isSponsored: false,
    status: "approved",
    ticketTypes: [
      { id: "t11", name: "Free", nameFr: "Gratuit", price: 0, currency: "FCFA", available: 2000 },
    ],
    latitude: 6.9004,
    longitude: 0.6237,
    createdAt: "2026-03-25",
  },
  {
    id: "7",
    title: "Nuit Culturelle de Kara",
    titleFr: "Nuit Culturelle de Kara",
    description: "An evening celebrating the rich culture of northern Togo",
    descriptionFr: "Une soirée célébrant la riche culture du nord du Togo",
    date: "2026-07-12",
    time: "19:00",
    venue: "Centre Culturel de Kara",
    venueId: "v7",
    city: "Kara",
    category: "culture",
    imageUrl: "https://images.unsplash.com/photo-1510925758641-869d353cecc7?w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1510925758641-869d353cecc7?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1547153760-18fc86324498?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1504680177321-2e6a879aac86?w=800&auto=format&fit=crop",
    ],
    price: 1000,
    currency: "FCFA",
    isSponsored: false,
    status: "approved",
    ticketTypes: [
      { id: "t12", name: "Standard", nameFr: "Standard", price: 1000, currency: "FCFA", available: 300 },
    ],
    latitude: 9.5511,
    longitude: 1.1811,
    createdAt: "2026-04-01",
  },
  {
    id: "8",
    title: "Stade de Kégué: ASKO vs ASCK",
    titleFr: "Stade de Kégué : ASKO vs ASCK",
    description: "Top Togolese football league derby at the national stadium",
    descriptionFr: "Derby du championnat togolais de football au stade national",
    date: "2026-07-25",
    time: "16:00",
    venue: "Stade de Kégué",
    venueId: "v8",
    city: "Lomé",
    category: "sport",
    imageUrl: "https://images.unsplash.com/photo-1459865264687-595d652de67e?w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1459865264687-595d652de67e?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=800&auto=format&fit=crop",
    ],
    price: 1000,
    currency: "FCFA",
    isSponsored: true,
    status: "approved",
    ticketTypes: [
      { id: "t13", name: "Tribune VIP", nameFr: "Tribune VIP", price: 5000, currency: "FCFA", available: 200 },
      { id: "t14", name: "Tribune", nameFr: "Tribune", price: 1000, currency: "FCFA", available: 10000 },
    ],
    latitude: 6.1467,
    longitude: 1.2494,
    createdAt: "2026-04-05",
  },
];

export const MOCK_VENUES = [
  {
    id: "v1",
    name: "Club Byblos",
    type: "Nightclub",
    city: "Lomé",
    address: "Boulevard du Mono, Lomé",
    imageUrl: "https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=800&auto=format&fit=crop",
    description: "Le club incontournable de Lomé avec les meilleurs DJs d'Afrique de l'Ouest",
    isVerified: true,
    latitude: 6.1302,
    longitude: 1.2199,
    ownerId: "u1",
    createdAt: "2025-01-01",
  },
  {
    id: "v2",
    name: "Palais des Congrès de Lomé",
    type: "Concert Hall",
    city: "Lomé",
    address: "Route de l'Aviation, Lomé",
    imageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&auto=format&fit=crop",
    description: "Grande salle de spectacle et de conférences au cœur de Lomé",
    isVerified: true,
    latitude: 6.1328,
    longitude: 1.2167,
    ownerId: "u2",
    createdAt: "2025-01-02",
  },
  {
    id: "v3",
    name: "Alliance Française de Lomé",
    type: "Cultural Center",
    city: "Lomé",
    address: "Avenue du 24 Janvier, Lomé",
    imageUrl: "https://images.unsplash.com/photo-1510925758641-869d353cecc7?w=800&auto=format&fit=crop",
    description: "Espace culturel franco-togolais, théâtre, expositions et concerts",
    isVerified: true,
    latitude: 6.1374,
    longitude: 1.2111,
    ownerId: "u3",
    createdAt: "2025-01-03",
  },
  {
    id: "v4",
    name: "Place de l'Indépendance",
    type: "Cultural Center",
    city: "Lomé",
    address: "Boulevard du 13 Janvier, Lomé",
    imageUrl: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&auto=format&fit=crop",
    description: "Place emblématique de Lomé, cœur des festivités nationales",
    isVerified: true,
    latitude: 6.1256,
    longitude: 1.2254,
    ownerId: "u4",
    createdAt: "2025-01-04",
  },
  {
    id: "v5",
    name: "Le Byblos Beach Aného",
    type: "Beach Club",
    city: "Aného",
    address: "Front de mer, Aného",
    imageUrl: "https://images.unsplash.com/photo-1535916707207-35a787c3f3ee?w=800&auto=format&fit=crop",
    description: "Club de plage sur la côte togolaise, ambiance festive et vue sur l'océan",
    isVerified: true,
    latitude: 6.2310,
    longitude: 1.5800,
    ownerId: "u5",
    createdAt: "2025-01-05",
  },
  {
    id: "v6",
    name: "Espace Culturel Kpalimé",
    type: "Cultural Center",
    city: "Kpalimé",
    address: "Centre-ville, Kpalimé",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop",
    description: "Espace dédié aux arts et traditions de la région des Plateaux",
    isVerified: false,
    latitude: 6.9004,
    longitude: 0.6237,
    ownerId: "u6",
    createdAt: "2025-01-06",
  },
  {
    id: "v7",
    name: "Centre Culturel de Kara",
    type: "Cultural Center",
    city: "Kara",
    address: "Avenue Yagounou, Kara",
    imageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&auto=format&fit=crop",
    description: "Principal espace culturel du nord du Togo, spectacles et expositions",
    isVerified: true,
    latitude: 9.5511,
    longitude: 1.1811,
    ownerId: "u7",
    createdAt: "2025-01-07",
  },
  {
    id: "v8",
    name: "Stade de Kégué",
    type: "Stadium",
    city: "Lomé",
    address: "Quartier Kégué, Lomé",
    imageUrl: "https://images.unsplash.com/photo-1459865264687-595d652de67e?w=800&auto=format&fit=crop",
    description: "Stade national du Togo, 20 000 places, concerts et matchs",
    isVerified: true,
    latitude: 6.1467,
    longitude: 1.2494,
    ownerId: "u8",
    createdAt: "2025-01-08",
  },
];

export const MOCK_SUBSCRIPTION_PLANS = [
  {
    id: "free",
    name: "Free",
    nameFr: "Gratuit",
    monthlyPriceFCFA: 0,
    features: ["1 active event", "Basic analytics", "Standard listing"],
    featuresFr: ["1 événement actif", "Analyses de base", "Listing standard"],
    isPopular: false,
  },
  {
    id: "pro",
    name: "Pro",
    nameFr: "Pro",
    monthlyPriceFCFA: 15000,
    features: [
      "10 active events",
      "Advanced analytics",
      "Featured listing",
      "Priority support",
      "Mobile money payments",
    ],
    featuresFr: [
      "10 événements actifs",
      "Analyses avancées",
      "Listing mis en avant",
      "Support prioritaire",
      "Paiements mobile money",
    ],
    isPopular: true,
  },
  {
    id: "premium",
    name: "Premium",
    nameFr: "Premium",
    monthlyPriceFCFA: 45000,
    features: [
      "Unlimited events",
      "Full analytics suite",
      "Sponsored badge",
      "Dedicated account manager",
      "Custom branding",
      "API access",
    ],
    featuresFr: [
      "Événements illimités",
      "Suite d'analyses complète",
      "Badge sponsorisé",
      "Account manager dédié",
      "Branding personnalisé",
      "Accès API",
    ],
    isPopular: false,
  },
];
