export type CategoryKey =
  | "concerts"
  | "nightclubs"
  | "bars"
  | "restaurants"
  | "beach"
  | "cinema"
  | "hotels"
  | "festivals"
  | "sport"
  | "culture"
  | "comedy"
  | "liveMusic";

export const CATEGORIES: { key: CategoryKey; icon: string; color: string }[] = [
  { key: "concerts", icon: "musical-notes", color: "#E8735A" },
  { key: "nightclubs", icon: "wine", color: "#9B8FE8" },
  { key: "bars", icon: "beer", color: "#D4AF37" },
  { key: "restaurants", icon: "restaurant", color: "#4CAF82" },
  { key: "beach", icon: "sunny", color: "#5AB4E8" },
  { key: "cinema", icon: "film", color: "#E85A9B" },
  { key: "hotels", icon: "bed", color: "#8FE8B0" },
  { key: "festivals", icon: "sparkles", color: "#E8C85A" },
  { key: "sport", icon: "football", color: "#5AE875" },
  { key: "culture", icon: "library", color: "#B85AE8" },
  { key: "comedy", icon: "happy", color: "#E8985A" },
  { key: "liveMusic", icon: "mic", color: "#5A9BE8" },
];

export const VENUE_TYPES = [
  "Nightclub",
  "Bar",
  "Restaurant",
  "Concert Hall",
  "Beach Club",
  "Cinema",
  "Hotel",
  "Stadium",
  "Cultural Center",
  "Comedy Club",
];

export const MOCK_CITIES = [
  { id: "abidjan", name: "Abidjan", country: "Côte d'Ivoire" },
  { id: "dakar", name: "Dakar", country: "Sénégal" },
  { id: "accra", name: "Accra", country: "Ghana" },
  { id: "lagos", name: "Lagos", country: "Nigeria" },
  { id: "lome", name: "Lomé", country: "Togo" },
  { id: "cotonou", name: "Cotonou", country: "Bénin" },
  { id: "ouagadougou", name: "Ouagadougou", country: "Burkina Faso" },
  { id: "bamako", name: "Bamako", country: "Mali" },
  { id: "nairobi", name: "Nairobi", country: "Kenya" },
  { id: "casablanca", name: "Casablanca", country: "Maroc" },
];

export const MOCK_EVENTS = [
  {
    id: "1",
    title: "Afrobeats Night",
    titleFr: "Nuit Afrobeats",
    description: "The biggest afrobeats party of the year with top African DJs",
    descriptionFr: "La plus grande fête afrobeats de l'année avec les meilleurs DJs africains",
    date: "2026-04-15",
    time: "22:00",
    venue: "Club Éléphant Blanc",
    venueId: "v1",
    city: "Abidjan",
    category: "nightclubs",
    imageUrl: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800&auto=format&fit=crop",
    price: 15000,
    currency: "FCFA",
    isSponsored: true,
    status: "approved",
    ticketTypes: [
      { id: "t1", name: "VIP", nameFr: "VIP", price: 50000, currency: "FCFA", available: 50 },
      { id: "t2", name: "Standard", nameFr: "Standard", price: 15000, currency: "FCFA", available: 200 },
    ],
    latitude: 5.3599517,
    longitude: -4.0082563,
    createdAt: "2026-03-01",
  },
  {
    id: "2",
    title: "Sauti Sol Live Concert",
    titleFr: "Concert Live Sauti Sol",
    description: "East African music icons Sauti Sol perform live",
    descriptionFr: "Les icônes de la musique est-africaine Sauti Sol en concert live",
    date: "2026-04-22",
    time: "20:00",
    venue: "Palais de la Culture",
    venueId: "v2",
    city: "Abidjan",
    category: "concerts",
    imageUrl: "https://images.unsplash.com/photo-1501386761578-eaa54b9f4bcd?w=800&auto=format&fit=crop",
    price: 25000,
    currency: "FCFA",
    isSponsored: false,
    status: "approved",
    ticketTypes: [
      { id: "t3", name: "VIP Gold", nameFr: "VIP Or", price: 100000, currency: "FCFA", available: 20 },
      { id: "t4", name: "VIP", nameFr: "VIP", price: 50000, currency: "FCFA", available: 100 },
      { id: "t5", name: "Standard", nameFr: "Standard", price: 25000, currency: "FCFA", available: 500 },
    ],
    latitude: 5.3470,
    longitude: -4.0148,
    createdAt: "2026-03-05",
  },
  {
    id: "3",
    title: "Dakar Comedy Night",
    titleFr: "Soirée Comédie Dakar",
    description: "The best West African comedians on one stage",
    descriptionFr: "Les meilleurs comédiens d'Afrique de l'Ouest sur une scène",
    date: "2026-05-01",
    time: "20:30",
    venue: "Théâtre Daniel Sorano",
    venueId: "v3",
    city: "Dakar",
    category: "comedy",
    imageUrl: "https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800&auto=format&fit=crop",
    price: 10000,
    currency: "FCFA",
    isSponsored: false,
    status: "approved",
    ticketTypes: [
      { id: "t6", name: "VIP", nameFr: "VIP", price: 30000, currency: "FCFA", available: 30 },
      { id: "t7", name: "Standard", nameFr: "Standard", price: 10000, currency: "FCFA", available: 200 },
    ],
    latitude: 14.6928,
    longitude: -17.4467,
    createdAt: "2026-03-10",
  },
  {
    id: "4",
    title: "Festival des Arts de Lomé",
    titleFr: "Festival des Arts de Lomé",
    description: "Annual cultural festival celebrating African art and music",
    descriptionFr: "Festival culturel annuel célébrant l'art et la musique africains",
    date: "2026-05-10",
    time: "16:00",
    venue: "Place de l'Indépendance",
    venueId: "v4",
    city: "Lomé",
    category: "festivals",
    imageUrl: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&auto=format&fit=crop",
    price: 0,
    currency: "FCFA",
    isSponsored: true,
    status: "approved",
    ticketTypes: [
      { id: "t8", name: "Free", nameFr: "Gratuit", price: 0, currency: "FCFA", available: 1000 },
    ],
    latitude: 6.1256,
    longitude: 1.2254,
    createdAt: "2026-03-15",
  },
  {
    id: "5",
    title: "Accra Beach Party",
    titleFr: "Fête de la Plage d'Accra",
    description: "Epic beach party with afro-house music and ocean views",
    descriptionFr: "Fête épique sur la plage avec de la musique afro-house",
    date: "2026-06-05",
    time: "14:00",
    venue: "Laboma Beach Resort",
    venueId: "v5",
    city: "Accra",
    category: "beach",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop",
    price: 20000,
    currency: "FCFA",
    isSponsored: true,
    status: "approved",
    ticketTypes: [
      { id: "t9", name: "VIP Table", nameFr: "Table VIP", price: 150000, currency: "FCFA", available: 10 },
      { id: "t10", name: "Standard", nameFr: "Standard", price: 20000, currency: "FCFA", available: 300 },
    ],
    latitude: 5.5502,
    longitude: -0.2174,
    createdAt: "2026-03-20",
  },
  {
    id: "6",
    title: "Lagos Food Festival",
    titleFr: "Festival Gastronomique de Lagos",
    description: "Discover the best West African cuisine",
    descriptionFr: "Découvrez la meilleure cuisine d'Afrique de l'Ouest",
    date: "2026-06-20",
    time: "12:00",
    venue: "Eko Hotel",
    venueId: "v6",
    city: "Lagos",
    category: "restaurants",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop",
    price: 35000,
    currency: "FCFA",
    isSponsored: false,
    status: "approved",
    ticketTypes: [
      { id: "t11", name: "Standard", nameFr: "Standard", price: 35000, currency: "FCFA", available: 400 },
    ],
    latitude: 6.4298,
    longitude: 3.4204,
    createdAt: "2026-03-25",
  },
];

export const MOCK_VENUES = [
  {
    id: "v1",
    name: "Club Éléphant Blanc",
    type: "Nightclub",
    city: "Abidjan",
    address: "Zone 4, Abidjan",
    imageUrl: "https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=800&auto=format&fit=crop",
    description: "The premier nightclub in Abidjan",
    isVerified: true,
    latitude: 5.3599517,
    longitude: -4.0082563,
    ownerId: "u1",
    createdAt: "2025-01-01",
  },
  {
    id: "v2",
    name: "Palais de la Culture",
    type: "Concert Hall",
    city: "Abidjan",
    address: "Treichville, Abidjan",
    imageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&auto=format&fit=crop",
    description: "Cultural venue for concerts and events",
    isVerified: true,
    latitude: 5.3470,
    longitude: -4.0148,
    ownerId: "u2",
    createdAt: "2025-01-02",
  },
  {
    id: "v3",
    name: "Théâtre Daniel Sorano",
    type: "Cultural Center",
    city: "Dakar",
    address: "Avenue Albert Sarraut, Dakar",
    imageUrl: "https://images.unsplash.com/photo-1510925758641-869d353cecc7?w=800&auto=format&fit=crop",
    description: "Historic theater in Dakar's heart",
    isVerified: true,
    latitude: 14.6928,
    longitude: -17.4467,
    ownerId: "u3",
    createdAt: "2025-01-03",
  },
  {
    id: "v4",
    name: "Place de l'Indépendance",
    type: "Stadium",
    city: "Lomé",
    address: "Boulevard du 13 Janvier, Lomé",
    imageUrl: "https://images.unsplash.com/photo-1459865264687-595d652de67e?w=800&auto=format&fit=crop",
    description: "Historic independence square",
    isVerified: true,
    latitude: 6.1256,
    longitude: 1.2254,
    ownerId: "u4",
    createdAt: "2025-01-04",
  },
  {
    id: "v5",
    name: "Laboma Beach Resort",
    type: "Beach Club",
    city: "Accra",
    address: "La, Accra",
    imageUrl: "https://images.unsplash.com/photo-1535916707207-35a787c3f3ee?w=800&auto=format&fit=crop",
    description: "Premium beach resort for events",
    isVerified: false,
    latitude: 5.5502,
    longitude: -0.2174,
    ownerId: "u5",
    createdAt: "2025-01-05",
  },
  {
    id: "v6",
    name: "Eko Hotel",
    type: "Hotel",
    city: "Lagos",
    address: "Eko Hotels & Suites, Victoria Island",
    imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop",
    description: "Luxury hotel venue",
    isVerified: true,
    latitude: 6.4298,
    longitude: 3.4204,
    ownerId: "u6",
    createdAt: "2025-01-06",
  },
];

export const MOCK_SUBSCRIPTION_PLANS = [
  {
    id: "free",
    name: "Free",
    nameFr: "Gratuit",
    monthlyPriceFCFA: 0,
    features: ["1 active event", "Basic analytics", "Standard listing"],
    featuresFr: ["1 événement actif", "Analyses de base", "Listing standard"],
    isPopular: false,
  },
  {
    id: "pro",
    name: "Pro",
    nameFr: "Pro",
    monthlyPriceFCFA: 15000,
    features: [
      "10 active events",
      "Advanced analytics",
      "Featured listing",
      "Priority support",
      "Mobile money payments",
    ],
    featuresFr: [
      "10 événements actifs",
      "Analyses avancées",
      "Listing mis en avant",
      "Support prioritaire",
      "Paiements mobile money",
    ],
    isPopular: true,
  },
  {
    id: "premium",
    name: "Premium",
    nameFr: "Premium",
    monthlyPriceFCFA: 45000,
    features: [
      "Unlimited events",
      "Full analytics suite",
      "Sponsored badge",
      "Dedicated account manager",
      "Custom branding",
      "API access",
    ],
    featuresFr: [
      "Événements illimités",
      "Suite d'analyses complète",
      "Badge sponsorisé",
      "Account manager dédié",
      "Branding personnalisé",
      "Accès API",
    ],
    isPopular: false,
  },
];
