export type CategoryKey =
  | "concerts"
  | "nightclubs"
  | "bars"
  | "restaurants"
  | "beach"
  | "cinema"
  | "hotels"
  | "festivals"
  | "sport"
  | "culture"
  | "comedy"
  | "liveMusic";

export const CATEGORIES: { key: CategoryKey; icon: string; color: string }[] = [
  { key: "concerts", icon: "musical-notes", color: "#E8735A" },
  { key: "nightclubs", icon: "wine", color: "#9B8FE8" },
  { key: "bars", icon: "beer", color: "#D4AF37" },
  { key: "restaurants", icon: "restaurant", color: "#4CAF82" },
  { key: "beach", icon: "sunny", color: "#5AB4E8" },
  { key: "cinema", icon: "film", color: "#E85A9B" },
  { key: "hotels", icon: "bed", color: "#8FE8B0" },
  { key: "festivals", icon: "sparkles", color: "#E8C85A" },
  { key: "sport", icon: "football", color: "#5AE875" },
  { key: "culture", icon: "library", color: "#B85AE8" },
  { key: "comedy", icon: "happy", color: "#E8985A" },
  { key: "liveMusic", icon: "mic", color: "#5A9BE8" },
];

export const VENUE_TYPES = [
  "Nightclub",
  "Bar",
  "Restaurant",
  "Concert Hall",
  "Beach Club",
  "Cinema",
  "Hotel",
  "Stadium",
  "Cultural Center",
  "Comedy Club",
];

export const MOCK_CITIES = [
  { id: "lome",      name: "Lomé",      country: "Togo", emoji: "🏙️", latitude: 6.1374,  longitude: 1.2123 },
  { id: "kpalime",   name: "Kpalimé",   country: "Togo", emoji: "🌿", latitude: 6.9004,  longitude: 0.6237 },
  { id: "kara",      name: "Kara",      country: "Togo", emoji: "🎭", latitude: 9.5511,  longitude: 1.1811 },
  { id: "atakpame",  name: "Atakpamé",  country: "Togo", emoji: "🎵", latitude: 7.5328,  longitude: 1.1244 },
  { id: "sokode",    name: "Sokodé",    country: "Togo", emoji: "🎪", latitude: 8.9833,  longitude: 1.1333 },
  { id: "aneho",     name: "Aného",     country: "Togo", emoji: "🏖️", latitude: 6.2333,  longitude: 1.5833 },
];

export const MOCK_EVENTS = [
  {
    id: "1",
    title: "Afrobeats Night Lomé",
    titleFr: "Nuit Afrobeats Lomé",
    description: "The biggest afrobeats party of the year at Club Byblos with top Togolese DJs",
    descriptionFr: "La plus grande fête afrobeats de l'année au Club Byblos avec les meilleurs DJs togolais",
    date: "2026-04-15",
    time: "22:00",
    venue: "Club Byblos",
    venueId: "v1",
    city: "Lomé",
    category: "nightclubs",
    imageUrl: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800&auto=format&fit=crop",
    price: 5000,
    currency: "FCFA",
    isSponsored: true,
    status: "approved",
    ticketTypes: [
      { id: "t1", name: "VIP", nameFr: "VIP", price: 20000, currency: "FCFA", available: 50 },
      { id: "t2", name: "Standard", nameFr: "Standard", price: 5000, currency: "FCFA", available: 200 },
    ],
    latitude: 6.1302,
    longitude: 1.2199,
    createdAt: "2026-03-01",
  },
  {
    id: "2",
    title: "Gospel Live at Palais des Congrès",
    titleFr: "Gospel Live au Palais des Congrès",
    description: "Live gospel concert featuring Togo's top gospel artists",
    descriptionFr: "Concert gospel live avec les meilleurs artistes gospel du Togo",
    date: "2026-04-22",
    time: "19:00",
    venue: "Palais des Congrès de Lomé",
    venueId: "v2",
    city: "Lomé",
    category: "concerts",
    imageUrl: "https://images.unsplash.com/photo-1501386761578-eaa54b9f4bcd?w=800&auto=format&fit=crop",
    price: 3000,
    currency: "FCFA",
    isSponsored: false,
    status: "approved",
    ticketTypes: [
      { id: "t3", name: "VIP Gold", nameFr: "VIP Or", price: 15000, currency: "FCFA", available: 20 },
      { id: "t4", name: "VIP", nameFr: "VIP", price: 8000, currency: "FCFA", available: 100 },
      { id: "t5", name: "Standard", nameFr: "Standard", price: 3000, currency: "FCFA", available: 500 },
    ],
    latitude: 6.1328,
    longitude: 1.2167,
    createdAt: "2026-03-05",
  },
  {
    id: "3",
    title: "Comedy Night at Alliance Française",
    titleFr: "Soirée Comédie à l'Alliance Française",
    description: "The best Togolese comedians on one stage",
    descriptionFr: "Les meilleurs comédiens togolais sur une scène",
    date: "2026-05-01",
    time: "20:30",
    venue: "Alliance Française de Lomé",
    venueId: "v3",
    city: "Lomé",
    category: "comedy",
    imageUrl: "https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800&auto=format&fit=crop",
    price: 2000,
    currency: "FCFA",
    isSponsored: false,
    status: "approved",
    ticketTypes: [
      { id: "t6", name: "VIP", nameFr: "VIP", price: 6000, currency: "FCFA", available: 30 },
      { id: "t7", name: "Standard", nameFr: "Standard", price: 2000, currency: "FCFA", available: 200 },
    ],
    latitude: 6.1374,
    longitude: 1.2111,
    createdAt: "2026-03-10",
  },
  {
    id: "4",
    title: "Festival des Arts de Lomé",
    titleFr: "Festival des Arts de Lomé",
    description: "Annual cultural festival celebrating Togolese art, music and traditions",
    descriptionFr: "Festival culturel annuel célébrant l'art, la musique et les traditions togolaises",
    date: "2026-05-10",
    time: "16:00",
    venue: "Place de l'Indépendance",
    venueId: "v4",
    city: "Lomé",
    category: "festivals",
    imageUrl: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&auto=format&fit=crop",
    price: 0,
    currency: "FCFA",
    isSponsored: true,
    status: "approved",
    ticketTypes: [
      { id: "t8", name: "Free", nameFr: "Gratuit", price: 0, currency: "FCFA", available: 5000 },
    ],
    latitude: 6.1256,
    longitude: 1.2254,
    createdAt: "2026-03-15",
  },
  {
    id: "5",
    title: "Beach Party Aného",
    titleFr: "Soirée Plage d'Aného",
    description: "Epic beach party on the Togolese coast with afro-house music",
    descriptionFr: "Soirée épique sur la côte togolaise avec de la musique afro-house",
    date: "2026-06-05",
    time: "14:00",
    venue: "Le Byblos Beach Aného",
    venueId: "v5",
    city: "Aného",
    category: "beach",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop",
    price: 3000,
    currency: "FCFA",
    isSponsored: true,
    status: "approved",
    ticketTypes: [
      { id: "t9", name: "VIP Table", nameFr: "Table VIP", price: 25000, currency: "FCFA", available: 10 },
      { id: "t10", name: "Standard", nameFr: "Standard", price: 3000, currency: "FCFA", available: 300 },
    ],
    latitude: 6.2310,
    longitude: 1.5800,
    createdAt: "2026-03-20",
  },
  {
    id: "6",
    title: "Festival des Cascades de Kpalimé",
    titleFr: "Festival des Cascades de Kpalimé",
    description: "Discover Togolese cuisine and cultural traditions at the foot of the waterfalls",
    descriptionFr: "Découvrez la cuisine et les traditions culturelles togolaises au pied des cascades",
    date: "2026-06-20",
    time: "10:00",
    venue: "Espace Culturel Kpalimé",
    venueId: "v6",
    city: "Kpalimé",
    category: "culture",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop",
    price: 0,
    currency: "FCFA",
    isSponsored: false,
    status: "approved",
    ticketTypes: [
      { id: "t11", name: "Free", nameFr: "Gratuit", price: 0, currency: "FCFA", available: 2000 },
    ],
    latitude: 6.9004,
    longitude: 0.6237,
    createdAt: "2026-03-25",
  },
  {
    id: "7",
    title: "Nuit Culturelle de Kara",
    titleFr: "Nuit Culturelle de Kara",
    description: "An evening celebrating the rich culture of northern Togo",
    descriptionFr: "Une soirée célébrant la riche culture du nord du Togo",
    date: "2026-07-12",
    time: "19:00",
    venue: "Centre Culturel de Kara",
    venueId: "v7",
    city: "Kara",
    category: "culture",
    imageUrl: "https://images.unsplash.com/photo-1510925758641-869d353cecc7?w=800&auto=format&fit=crop",
    price: 1000,
    currency: "FCFA",
    isSponsored: false,
    status: "approved",
    ticketTypes: [
      { id: "t12", name: "Standard", nameFr: "Standard", price: 1000, currency: "FCFA", available: 300 },
    ],
    latitude: 9.5511,
    longitude: 1.1811,
    createdAt: "2026-04-01",
  },
  {
    id: "8",
    title: "Stade de Kégué: ASKO vs ASCK",
    titleFr: "Stade de Kégué : ASKO vs ASCK",
    description: "Top Togolese football league derby at the national stadium",
    descriptionFr: "Derby du championnat togolais de football au stade national",
    date: "2026-07-25",
    time: "16:00",
    venue: "Stade de Kégué",
    venueId: "v8",
    city: "Lomé",
    category: "sport",
    imageUrl: "https://images.unsplash.com/photo-1459865264687-595d652de67e?w=800&auto=format&fit=crop",
    price: 1000,
    currency: "FCFA",
    isSponsored: true,
    status: "approved",
    ticketTypes: [
      { id: "t13", name: "Tribune VIP", nameFr: "Tribune VIP", price: 5000, currency: "FCFA", available: 200 },
      { id: "t14", name: "Tribune", nameFr: "Tribune", price: 1000, currency: "FCFA", available: 10000 },
    ],
    latitude: 6.1467,
    longitude: 1.2494,
    createdAt: "2026-04-05",
  },
];

export const MOCK_VENUES = [
  {
    id: "v1",
    name: "Club Byblos",
    type: "Nightclub",
    city: "Lomé",
    address: "Boulevard du Mono, Lomé",
    imageUrl: "https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=800&auto=format&fit=crop",
    description: "Le club incontournable de Lomé avec les meilleurs DJs d'Afrique de l'Ouest",
    isVerified: true,
    latitude: 6.1302,
    longitude: 1.2199,
    ownerId: "u1",
    createdAt: "2025-01-01",
  },
  {
    id: "v2",
    name: "Palais des Congrès de Lomé",
    type: "Concert Hall",
    city: "Lomé",
    address: "Route de l'Aviation, Lomé",
    imageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&auto=format&fit=crop",
    description: "Grande salle de spectacle et de conférences au cœur de Lomé",
    isVerified: true,
    latitude: 6.1328,
    longitude: 1.2167,
    ownerId: "u2",
    createdAt: "2025-01-02",
  },
  {
    id: "v3",
    name: "Alliance Française de Lomé",
    type: "Cultural Center",
    city: "Lomé",
    address: "Avenue du 24 Janvier, Lomé",
    imageUrl: "https://images.unsplash.com/photo-1510925758641-869d353cecc7?w=800&auto=format&fit=crop",
    description: "Espace culturel franco-togolais, théâtre, expositions et concerts",
    isVerified: true,
    latitude: 6.1374,
    longitude: 1.2111,
    ownerId: "u3",
    createdAt: "2025-01-03",
  },
  {
    id: "v4",
    name: "Place de l'Indépendance",
    type: "Cultural Center",
    city: "Lomé",
    address: "Boulevard du 13 Janvier, Lomé",
    imageUrl: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&auto=format&fit=crop",
    description: "Place emblématique de Lomé, cœur des festivités nationales",
    isVerified: true,
    latitude: 6.1256,
    longitude: 1.2254,
    ownerId: "u4",
    createdAt: "2025-01-04",
  },
  {
    id: "v5",
    name: "Le Byblos Beach Aného",
    type: "Beach Club",
    city: "Aného",
    address: "Front de mer, Aného",
    imageUrl: "https://images.unsplash.com/photo-1535916707207-35a787c3f3ee?w=800&auto=format&fit=crop",
    description: "Club de plage sur la côte togolaise, ambiance festive et vue sur l'océan",
    isVerified: true,
    latitude: 6.2310,
    longitude: 1.5800,
    ownerId: "u5",
    createdAt: "2025-01-05",
  },
  {
    id: "v6",
    name: "Espace Culturel Kpalimé",
    type: "Cultural Center",
    city: "Kpalimé",
    address: "Centre-ville, Kpalimé",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop",
    description: "Espace dédié aux arts et traditions de la région des Plateaux",
    isVerified: false,
    latitude: 6.9004,
    longitude: 0.6237,
    ownerId: "u6",
    createdAt: "2025-01-06",
  },
  {
    id: "v7",
    name: "Centre Culturel de Kara",
    type: "Cultural Center",
    city: "Kara",
    address: "Avenue Yagounou, Kara",
    imageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&auto=format&fit=crop",
    description: "Principal espace culturel du nord du Togo, spectacles et expositions",
    isVerified: true,
    latitude: 9.5511,
    longitude: 1.1811,
    ownerId: "u7",
    createdAt: "2025-01-07",
  },
  {
    id: "v8",
    name: "Stade de Kégué",
    type: "Stadium",
    city: "Lomé",
    address: "Quartier Kégué, Lomé",
    imageUrl: "https://images.unsplash.com/photo-1459865264687-595d652de67e?w=800&auto=format&fit=crop",
    description: "Stade national du Togo, 20 000 places, concerts et matchs",
    isVerified: true,
    latitude: 6.1467,
    longitude: 1.2494,
    ownerId: "u8",
    createdAt: "2025-01-08",
  },
];

export const MOCK_SUBSCRIPTION_PLANS = [
  {
    id: "free",
    name: "Free",
    nameFr: "Gratuit",
    monthlyPriceFCFA: 0,
    features: ["1 active event", "Basic analytics", "Standard listing"],
    featuresFr: ["1 événement actif", "Analyses de base", "Listing standard"],
    isPopular: false,
  },
  {
    id: "pro",
    name: "Pro",
    nameFr: "Pro",
    monthlyPriceFCFA: 15000,
    features: [
      "10 active events",
      "Advanced analytics",
      "Featured listing",
      "Priority support",
      "Mobile money payments",
    ],
    featuresFr: [
      "10 événements actifs",
      "Analyses avancées",
      "Listing mis en avant",
      "Support prioritaire",
      "Paiements mobile money",
    ],
    isPopular: true,
  },
  {
    id: "premium",
    name: "Premium",
    nameFr: "Premium",
    monthlyPriceFCFA: 45000,
    features: [
      "Unlimited events",
      "Full analytics suite",
      "Sponsored badge",
      "Dedicated account manager",
      "Custom branding",
      "API access",
    ],
    featuresFr: [
      "Événements illimités",
      "Suite d'analyses complète",
      "Badge sponsorisé",
      "Account manager dédié",
      "Branding personnalisé",
      "Accès API",
    ],
    isPopular: false,
  },
];
